name: One

on:
  pull_request:
    paths: 'src/**'
  workflow_dispatch:

jobs:
  one:
    name: One
    environment: One

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: echo "hi there one"
