name: Two

on:
  push:
    branches:
      - main
    paths: 'src/**'
  workflow_dispatch:

jobs:
  two:
    name: Two

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: echo "hi there two"
