name: Two

on:
  pull_request:
    paths: 'src/**'
  workflow_dispatch:

jobs:
  two:
    name: Two

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - run: echo "hi there two"
